### PR TITLE
#2 - fixed copyright section

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Please review this PR.

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, someone will review your pull request soon

**Comment by dmarkov** [comment]
@krzyk please review this PR

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@krzyk paid, thanks, added **16 mins** to your account, payment `50342650`; +16 added to your rating, at the moment it is: [+1962](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
